[project]
name = "inteligencja-obliczeniowa-w-analizie-danych-cyfrowych"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "easyai>=2.0.12",
    "gymnasium>=1.2.3",
    "imageio>=2.37.3",
    "imageio-ffmpeg>=0.6.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.8.0",
    "pandoc>=2.4",
    "pygame>=2.6.1",
    "rich>=15.0.0",
    "sb3-contrib>=2.8.0",
    "stable-baselines3[extra]>=2.8.0",
    "tqdm>=4.67.3",
]
